name: Build AsuraScans Extension

on:
  workflow_dispatch:    # allows you to click "Run workflow" manually
  push:                 # builds automatically on push
    paths:
      - "src/all/asurascans/**"
      - ".github/workflows/build-asurascans.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to Gradle
        run: chmod +x gradlew

      - name: Build ONLY AsuraScans
        run: ./gradlew :all:asurascans:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: asurascans-extension
          path: output/all/asurascans/*.apk
